// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"
	"database/sql"
)

const checkAllowedOriginExists = `-- name: CheckAllowedOriginExists :one
SELECT EXISTS(SELECT 1 FROM api_keys WHERE allowed_origin = ? AND is_dev = false)
`

func (q *Queries) CheckAllowedOriginExists(ctx context.Context, allowedOrigin sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAllowedOriginExists, allowedOrigin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE member_email = ? LIMIT 1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, memberEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, memberEmail)
	return err
}

const deleteAPIKeyById = `-- name: DeleteAPIKeyById :exec
DELETE FROM api_keys WHERE api_key_id = ? AND member_email = ?
`

type DeleteAPIKeyByIdParams struct {
	ApiKeyID    int32
	MemberEmail string
}

func (q *Queries) DeleteAPIKeyById(ctx context.Context, arg DeleteAPIKeyByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeyById, arg.ApiKeyID, arg.MemberEmail)
	return err
}

const getAPIKeyInfo = `-- name: GetAPIKeyInfo :one
SELECT api_key_id, member_email, api_key_hash, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE api_key_hash = ?
`

func (q *Queries) GetAPIKeyInfo(ctx context.Context, apiKeyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyInfo, apiKeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.MemberEmail,
		&i.ApiKeyHash,
		&i.Project,
		&i.AllowedOrigin,
		&i.IsDev,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyInfoWithEmail = `-- name: GetAPIKeyInfoWithEmail :one
SELECT api_key_id, member_email, api_key_hash, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE member_email = ?
`

func (q *Queries) GetAPIKeyInfoWithEmail(ctx context.Context, memberEmail string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyInfoWithEmail, memberEmail)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.MemberEmail,
		&i.ApiKeyHash,
		&i.Project,
		&i.AllowedOrigin,
		&i.IsDev,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAllAPIKeyHashes = `-- name: GetAllAPIKeyHashes :many
SELECT api_key_hash FROM api_keys
`

func (q *Queries) GetAllAPIKeyHashes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllAPIKeyHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var api_key_hash string
		if err := rows.Scan(&api_key_hash); err != nil {
			return nil, err
		}
		items = append(items, api_key_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailsInAPIKey = `-- name: GetEmailsInAPIKey :many
SELECT member_email FROM api_keys
`

func (q *Queries) GetEmailsInAPIKey(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEmailsInAPIKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_email string
		if err := rows.Scan(&member_email); err != nil {
			return nil, err
		}
		items = append(items, member_email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByEmail = `-- name: ListAPIKeysByEmail :many
SELECT api_key_id, member_email, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE member_email = ? ORDER BY created_at DESC
`

type ListAPIKeysByEmailRow struct {
	ApiKeyID      int32
	MemberEmail   string
	Project       sql.NullString
	AllowedOrigin sql.NullString
	IsDev         bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
	ExpiresAt     sql.NullTime
}

func (q *Queries) ListAPIKeysByEmail(ctx context.Context, memberEmail string) ([]ListAPIKeysByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByEmail, memberEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByEmailRow
	for rows.Next() {
		var i ListAPIKeysByEmailRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.MemberEmail,
			&i.Project,
			&i.AllowedOrigin,
			&i.IsDev,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeAPIKey = `-- name: StoreAPIKey :exec
INSERT INTO api_keys (
    member_email,
    api_key_hash,
    project,
    allowed_origin,
    is_dev,
    is_admin,
    expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type StoreAPIKeyParams struct {
	MemberEmail   string
	ApiKeyHash    string
	Project       sql.NullString
	AllowedOrigin sql.NullString
	IsDev         bool
	IsAdmin       bool
	ExpiresAt     sql.NullTime
}

func (q *Queries) StoreAPIKey(ctx context.Context, arg StoreAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, storeAPIKey,
		arg.MemberEmail,
		arg.ApiKeyHash,
		arg.Project,
		arg.AllowedOrigin,
		arg.IsDev,
		arg.IsAdmin,
		arg.ExpiresAt,
	)
	return err
}
