// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package repository

import (
	"context"
	"database/sql"
)

const checkEmailIfMember = `-- name: CheckEmailIfMember :one
SELECT email FROM members WHERE email = ?
`

func (q *Queries) CheckEmailIfMember(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkEmailIfMember, email)
	var email_2 string
	err := row.Scan(&email_2)
	return email_2, err
}

const checkIdIfMember = `-- name: CheckIdIfMember :one
SELECT id FROM members WHERE id = ?
`

func (q *Queries) CheckIdIfMember(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkIdIfMember, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const getAllCommittees = `-- name: GetAllCommittees :many
SELECT c.committee_id, c.committee_name, c.committee_head, c.division_id FROM committees c
`

func (q *Queries) GetAllCommittees(ctx context.Context) ([]Committee, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommittees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Committee
	for rows.Next() {
		var i Committee
		if err := rows.Scan(
			&i.CommitteeID,
			&i.CommitteeName,
			&i.CommitteeHead,
			&i.DivisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDivisions = `-- name: GetAllDivisions :many
SELECT d.division_id, d.division_name, d.division_head FROM divisions d
`

func (q *Queries) GetAllDivisions(ctx context.Context) ([]Division, error) {
	rows, err := q.db.QueryContext(ctx, getAllDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Division
	for rows.Next() {
		var i Division
		if err := rows.Scan(&i.DivisionID, &i.DivisionName, &i.DivisionHead); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, email, full_name, nickname, position_id, committee_id, college, program,
       discord, interests, contact_number, fb_link, telegram, house_id, image_url
FROM members WHERE email = ?
`

type GetMemberByEmailRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
	HouseID       sql.NullInt32
	ImageUrl      sql.NullString
}

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (GetMemberByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberByEmail, email)
	var i GetMemberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.PositionID,
		&i.CommitteeID,
		&i.College,
		&i.Program,
		&i.Discord,
		&i.Interests,
		&i.ContactNumber,
		&i.FbLink,
		&i.Telegram,
		&i.HouseID,
		&i.ImageUrl,
	)
	return i, err
}

const getMemberInfo = `-- name: GetMemberInfo :one
SELECT
  m.id, m.email, m.full_name, m.nickname, m.image_url,
  c.committee_id, c.committee_name,
  d.division_id, d.division_name,
  p.position_id, p.position_name,
  h.name as house_name,
  m.contact_number, m.college, m.program,
  m.interests, m.discord, m.fb_link, m.telegram
FROM members m
LEFT JOIN committees c ON m.committee_id = c.committee_id
LEFT JOIN divisions d ON c.division_id = d.division_id
LEFT JOIN positions p ON m.position_id = p.position_id
LEFT JOIN houses h ON m.house_id = h.id
WHERE m.email = ?
`

type GetMemberInfoRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	ImageUrl      sql.NullString
	CommitteeID   sql.NullString
	CommitteeName sql.NullString
	DivisionID    sql.NullString
	DivisionName  sql.NullString
	PositionID    sql.NullString
	PositionName  sql.NullString
	HouseName     sql.NullString
	ContactNumber sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Interests     sql.NullString
	Discord       sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
}

func (q *Queries) GetMemberInfo(ctx context.Context, email string) (GetMemberInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberInfo, email)
	var i GetMemberInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.ImageUrl,
		&i.CommitteeID,
		&i.CommitteeName,
		&i.DivisionID,
		&i.DivisionName,
		&i.PositionID,
		&i.PositionName,
		&i.HouseName,
		&i.ContactNumber,
		&i.College,
		&i.Program,
		&i.Interests,
		&i.Discord,
		&i.FbLink,
		&i.Telegram,
	)
	return i, err
}

const getMemberInfoById = `-- name: GetMemberInfoById :one
SELECT
  m.id, m.email, m.full_name, m.nickname, m.image_url,
  c.committee_id, c.committee_name,
  d.division_id, d.division_name,
  p.position_id, p.position_name,
  h.name as house_name,
  m.contact_number, m.college, m.program,
  m.interests, m.discord, m.fb_link, m.telegram
FROM members m
LEFT JOIN committees c ON m.committee_id = c.committee_id
LEFT JOIN divisions d ON c.division_id = d.division_id
LEFT JOIN positions p ON m.position_id = p.position_id
LEFT JOIN houses h ON m.house_id = h.id
WHERE m.id = ?
`

type GetMemberInfoByIdRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	ImageUrl      sql.NullString
	CommitteeID   sql.NullString
	CommitteeName sql.NullString
	DivisionID    sql.NullString
	DivisionName  sql.NullString
	PositionID    sql.NullString
	PositionName  sql.NullString
	HouseName     sql.NullString
	ContactNumber sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Interests     sql.NullString
	Discord       sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
}

func (q *Queries) GetMemberInfoById(ctx context.Context, id int32) (GetMemberInfoByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberInfoById, id)
	var i GetMemberInfoByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.ImageUrl,
		&i.CommitteeID,
		&i.CommitteeName,
		&i.DivisionID,
		&i.DivisionName,
		&i.PositionID,
		&i.PositionName,
		&i.HouseName,
		&i.ContactNumber,
		&i.College,
		&i.Program,
		&i.Interests,
		&i.Discord,
		&i.FbLink,
		&i.Telegram,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT
    m.id,
    m.full_name,
    m.nickname,
    m.email,
    m.telegram,
    m.position_id,
    m.committee_id,
    m.college,
    m.program,
    m.discord,
    m.interests,
    m.contact_number,
    m.fb_link,
    m.image_url,
    h.name as house_name
FROM members m
LEFT JOIN houses h ON m.house_id = h.id
WHERE (? = '' OR FIND_IN_SET(m.position_id, ?))
  AND (? = '' OR FIND_IN_SET(m.committee_id, ?))
ORDER BY m.email
`

type ListMembersParams struct {
	PositionIds  string
	CommitteeIds string
}

type ListMembersRow struct {
	ID            int32
	FullName      string
	Nickname      sql.NullString
	Email         string
	Telegram      sql.NullString
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	HouseName     sql.NullString
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers,
		arg.PositionIds,
		arg.PositionIds,
		arg.CommitteeIds,
		arg.CommitteeIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Nickname,
			&i.Email,
			&i.Telegram,
			&i.PositionID,
			&i.CommitteeID,
			&i.College,
			&i.Program,
			&i.Discord,
			&i.Interests,
			&i.ContactNumber,
			&i.FbLink,
			&i.ImageUrl,
			&i.HouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberById = `-- name: UpdateMemberById :exec
UPDATE members SET
    full_name = ?,
    nickname = ?,
    email = ?,
    position_id = ?,
    committee_id = ?,
    college = ?,
    program = ?,
    house_id = ?,
    telegram = ?,
    discord = ?,
    interests = ?,
    contact_number = ?,
    fb_link = ?,
    image_url = ?
WHERE id = ?
`

type UpdateMemberByIdParams struct {
	FullName      string
	Nickname      sql.NullString
	Email         string
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	HouseID       sql.NullInt32
	Telegram      sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	ID            int32
}

func (q *Queries) UpdateMemberById(ctx context.Context, arg UpdateMemberByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberById,
		arg.FullName,
		arg.Nickname,
		arg.Email,
		arg.PositionID,
		arg.CommitteeID,
		arg.College,
		arg.Program,
		arg.HouseID,
		arg.Telegram,
		arg.Discord,
		arg.Interests,
		arg.ContactNumber,
		arg.FbLink,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}

const updateMemberSelf = `-- name: UpdateMemberSelf :exec
UPDATE members SET
    nickname = ?,
    telegram = ?,
    discord = ?,
    interests = ?,
    contact_number = ?,
    fb_link = ?,
    image_url = ?
WHERE id = ?
`

type UpdateMemberSelfParams struct {
	Nickname      sql.NullString
	Telegram      sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	ID            int32
}

func (q *Queries) UpdateMemberSelf(ctx context.Context, arg UpdateMemberSelfParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberSelf,
		arg.Nickname,
		arg.Telegram,
		arg.Discord,
		arg.Interests,
		arg.ContactNumber,
		arg.FbLink,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}
