// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type FileStatusesStatus string

const (
	FileStatusesStatusDRAFTING FileStatusesStatus = "DRAFTING"
	FileStatusesStatusDONE     FileStatusesStatus = "DONE"
	FileStatusesStatusREVISE   FileStatusesStatus = "REVISE"
	FileStatusesStatusAPPROVED FileStatusesStatus = "APPROVED"
)

func (e *FileStatusesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatusesStatus(s)
	case string:
		*e = FileStatusesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatusesStatus: %T", src)
	}
	return nil
}

type NullFileStatusesStatus struct {
	FileStatusesStatus FileStatusesStatus
	Valid              bool // Valid is true if FileStatusesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatusesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatusesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatusesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatusesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatusesStatus), nil
}

type ApiKey struct {
	ApiKeyID    int32
	MemberEmail string
	ApiKeyHash  string
	CreatedAt   sql.NullTime
	ExpiresAt   sql.NullTime
}

type Committee struct {
	CommitteeID   string
	CommitteeName string
	CommitteeHead sql.NullInt32
	DivisionID    sql.NullString
}

type Division struct {
	DivisionID   string
	DivisionName string
	DivisionHead sql.NullInt32
}

type DocuStatus struct {
	ID    string
	Title string
}

type DocumentTemplate struct {
	ID       int32
	DocTitle string
	DocKey   string
}

type Event struct {
	ID               int32
	Arn              string
	Name             string
	CommitteeID      string
	Type             sql.NullString
	NatureID         int32
	TermID           int32
	CreatedAt        sql.NullTime
	DurationID       sql.NullInt32
	BriefDescription sql.NullString
	Goals            sql.NullString
	Objectives       sql.NullString
	Strategies       sql.NullString
	Measures         sql.NullString
	BudgetAllocation sql.NullString
	Venue            sql.NullString
	DocuHead         sql.NullInt32
	FinHead          sql.NullInt32
}

type EventDate struct {
	ID        int32
	EventID   int32
	StartTime time.Time
	EndTime   time.Time
}

type EventDocuHead struct {
	EventID  int32
	MemberID int32
}

type EventDuration struct {
	ID   int32
	Name string
}

type EventFile struct {
	ID         int32
	EventID    int32
	FileKey    string
	FileOrder  int32
	FileStatus int32
}

type EventHead struct {
	EventID  int32
	MemberID int32
}

type EventNature struct {
	ID   int32
	Name string
}

type EventParticipant struct {
	EventID      int32
	StudentID    int32
	StudentName  sql.NullString
	StudentEmail sql.NullString
	Notes        sql.NullString
}

type EventTracker struct {
	EventID             int32
	PreactsDeadline     sql.NullTime
	PreactsStatus       string
	PostactsDeadline    sql.NullTime
	PostactsStatus      string
	DocuDriveID         sql.NullString
	FinDriveID          sql.NullString
	FinPreactsDeadline  sql.NullTime
	FinPreactsStatus    sql.NullString
	FinPostactsDeadline sql.NullTime
	FinPostactsStatus   sql.NullString
}

type EventType struct {
	ID   int32
	Name string
}

type FileStatus struct {
	FileKey string
	Status  NullFileStatusesStatus
}

type FinProcess struct {
	ID        int32
	TrackerID int32
	Process   string
}

type FinProcessRef struct {
	ID   string
	Name string
}

type FinStatus struct {
	ID    string
	Title string
}

type House struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
}

type Member struct {
	ID            int32
	FullName      string
	Nickname      sql.NullString
	Email         string
	Telegram      sql.NullString
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	HouseID       sql.NullInt32
}

type Position struct {
	PositionID   string
	PositionName string
}

type ProgressStatus struct {
	ID     int32
	Status string
}

type PubReqStatus struct {
	ID   string
	Name string
}

type PubRequest struct {
	ID          int32
	EventID     sql.NullInt32
	PubHead     sql.NullInt32
	PubType     sql.NullString
	PubDriveID  string
	PubStatus   sql.NullString
	PostingDate time.Time
	PubDetails  string
	PubContent  string
	Caption     string
	OpaNumbers  string
	ForPosting  bool
	CreatedAt   time.Time
	RequesterID sql.NullInt32
	Dimensions  sql.NullString
}

type Term struct {
	ID        int32
	Term      int32
	StartYear int32
	EndYear   int32
}
