// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type ApiKey struct {
	ApiKeyID    int32
	MemberEmail string
	ApiKeyHash  string
	CreatedAt   sql.NullTime
	ExpiresAt   sql.NullTime
}

type Committee struct {
	CommitteeID   string
	CommitteeName string
	CommitteeHead sql.NullInt32
	DivisionID    sql.NullString
}

type Division struct {
	DivisionID   string
	DivisionName string
	DivisionHead sql.NullInt32
}

type Member struct {
	ID          int32
	FullName    string
	Nickname    sql.NullString
	Email       string
	Telegram    sql.NullString
	PositionID  sql.NullString
	CommitteeID sql.NullString
	College     sql.NullString
	Program     sql.NullString
	Discord     sql.NullString
}

type Position struct {
	PositionID   string
	PositionName string
}
