// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const checkAllowedOriginExists = `-- name: CheckAllowedOriginExists :one
SELECT EXISTS(SELECT 1 FROM api_keys WHERE allowed_origin = ? AND is_dev = false)
`

func (q *Queries) CheckAllowedOriginExists(ctx context.Context, allowedOrigin sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAllowedOriginExists, allowedOrigin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEmailIfMember = `-- name: CheckEmailIfMember :one
SELECT email FROM members WHERE email = ?
`

func (q *Queries) CheckEmailIfMember(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkEmailIfMember, email)
	err := row.Scan(&email)
	return email, err
}

const checkIdIfMember = `-- name: CheckIdIfMember :one
SELECT id FROM members WHERE id = ?
`

func (q *Queries) CheckIdIfMember(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkIdIfMember, id)
	err := row.Scan(&id)
	return id, err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, member_id, expires_at, user_agent, ip_address)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	MemberID  int32
	ExpiresAt time.Time
	UserAgent sql.NullString
	IpAddress sql.NullString
}

// Session queries for web UI authentication
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.MemberID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE member_email = ? LIMIT 1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, memberEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, memberEmail)
	return err
}

const deleteAPIKeyById = `-- name: DeleteAPIKeyById :exec
DELETE FROM api_keys WHERE api_key_id = ? AND member_email = ?
`

type DeleteAPIKeyByIdParams struct {
	ApiKeyID    int32
	MemberEmail string
}

func (q *Queries) DeleteAPIKeyById(ctx context.Context, arg DeleteAPIKeyByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKeyById, arg.ApiKeyID, arg.MemberEmail)
	return err
}

const deleteAllSessionsForMember = `-- name: DeleteAllSessionsForMember :exec
DELETE FROM sessions WHERE member_id = ?
`

func (q *Queries) DeleteAllSessionsForMember(ctx context.Context, memberID int32) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsForMember, memberID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = ?, last_activity = NOW() WHERE id = ?
`

type ExtendSessionParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.ID)
	return err
}

const getAPIKeyInfo = `-- name: GetAPIKeyInfo :one
SELECT api_key_id, member_email, api_key_hash, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE api_key_hash = ?
`

func (q *Queries) GetAPIKeyInfo(ctx context.Context, apiKeyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyInfo, apiKeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.MemberEmail,
		&i.ApiKeyHash,
		&i.Project,
		&i.AllowedOrigin,
		&i.IsDev,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyInfoWithEmail = `-- name: GetAPIKeyInfoWithEmail :one
SELECT api_key_id, member_email, api_key_hash, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE member_email = ?
`

func (q *Queries) GetAPIKeyInfoWithEmail(ctx context.Context, memberEmail string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyInfoWithEmail, memberEmail)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.MemberEmail,
		&i.ApiKeyHash,
		&i.Project,
		&i.AllowedOrigin,
		&i.IsDev,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAllAPIKeyHashes = `-- name: GetAllAPIKeyHashes :many
SELECT api_key_hash FROM api_keys
`

func (q *Queries) GetAllAPIKeyHashes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllAPIKeyHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var api_key_hash string
		if err := rows.Scan(&api_key_hash); err != nil {
			return nil, err
		}
		items = append(items, api_key_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCommittees = `-- name: GetAllCommittees :many
SELECT c.committee_id, c.committee_name, c.committee_head, c.division_id FROM committees c
`

func (q *Queries) GetAllCommittees(ctx context.Context) ([]Committee, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommittees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Committee
	for rows.Next() {
		var i Committee
		if err := rows.Scan(
			&i.CommitteeID,
			&i.CommitteeName,
			&i.CommitteeHead,
			&i.DivisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDivisions = `-- name: GetAllDivisions :many
SELECT d.division_id, d.division_name, d.division_head FROM divisions d
`

func (q *Queries) GetAllDivisions(ctx context.Context) ([]Division, error) {
	rows, err := q.db.QueryContext(ctx, getAllDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Division
	for rows.Next() {
		var i Division
		if err := rows.Scan(&i.DivisionID, &i.DivisionName, &i.DivisionHead); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoles = `-- name: GetAllRoles :many

SELECT id, name, description FROM roles ORDER BY id
`

// RBAC: Role queries
func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailsInAPIKey = `-- name: GetEmailsInAPIKey :many
SELECT member_email FROM api_keys
`

func (q *Queries) GetEmailsInAPIKey(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEmailsInAPIKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_email string
		if err := rows.Scan(&member_email); err != nil {
			return nil, err
		}
		items = append(items, member_email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberAuthInfo = `-- name: GetMemberAuthInfo :one
SELECT id, position_id, committee_id FROM members WHERE email = ?
`

type GetMemberAuthInfoRow struct {
	ID          int32
	PositionID  sql.NullString
	CommitteeID sql.NullString
}

// lightweight query for authorization checks (no image_url dependency)
func (q *Queries) GetMemberAuthInfo(ctx context.Context, email string) (GetMemberAuthInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberAuthInfo, email)
	var i GetMemberAuthInfoRow
	err := row.Scan(&i.ID, &i.PositionID, &i.CommitteeID)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, email, full_name, nickname, position_id, committee_id, college, program,
       discord, interests, contact_number, fb_link, telegram, house_id, image_url
FROM members WHERE email = ?
`

type GetMemberByEmailRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
	HouseID       sql.NullInt32
	ImageUrl      sql.NullString
}

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (GetMemberByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberByEmail, email)
	var i GetMemberByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.PositionID,
		&i.CommitteeID,
		&i.College,
		&i.Program,
		&i.Discord,
		&i.Interests,
		&i.ContactNumber,
		&i.FbLink,
		&i.Telegram,
		&i.HouseID,
		&i.ImageUrl,
	)
	return i, err
}

const getMemberInfo = `-- name: GetMemberInfo :one
SELECT
  m.id, m.email, m.full_name, m.nickname, m.image_url,
  c.committee_id, c.committee_name,
  d.division_id, d.division_name,
  p.position_id, p.position_name,
  h.name as house_name,
  m.contact_number, m.college, m.program,
  m.interests, m.discord, m.fb_link, m.telegram
FROM members m
LEFT JOIN committees c ON m.committee_id = c.committee_id
LEFT JOIN divisions d ON c.division_id = d.division_id
LEFT JOIN positions p ON m.position_id = p.position_id
LEFT JOIN houses h ON m.house_id = h.id
WHERE m.email = ?
`

type GetMemberInfoRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	ImageUrl      sql.NullString
	CommitteeID   sql.NullString
	CommitteeName sql.NullString
	DivisionID    sql.NullString
	DivisionName  sql.NullString
	PositionID    sql.NullString
	PositionName  sql.NullString
	HouseName     sql.NullString
	ContactNumber sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Interests     sql.NullString
	Discord       sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
}

func (q *Queries) GetMemberInfo(ctx context.Context, email string) (GetMemberInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberInfo, email)
	var i GetMemberInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.ImageUrl,
		&i.CommitteeID,
		&i.CommitteeName,
		&i.DivisionID,
		&i.DivisionName,
		&i.PositionID,
		&i.PositionName,
		&i.HouseName,
		&i.ContactNumber,
		&i.College,
		&i.Program,
		&i.Interests,
		&i.Discord,
		&i.FbLink,
		&i.Telegram,
	)
	return i, err
}

const getMemberInfoById = `-- name: GetMemberInfoById :one
SELECT
  m.id, m.email, m.full_name, m.nickname, m.image_url,
  c.committee_id, c.committee_name,
  d.division_id, d.division_name,
  p.position_id, p.position_name,
  h.name as house_name,
  m.contact_number, m.college, m.program,
  m.interests, m.discord, m.fb_link, m.telegram
FROM members m
LEFT JOIN committees c ON m.committee_id = c.committee_id
LEFT JOIN divisions d ON c.division_id = d.division_id
LEFT JOIN positions p ON m.position_id = p.position_id
LEFT JOIN houses h ON m.house_id = h.id
WHERE m.id = ?
`

type GetMemberInfoByIdRow struct {
	ID            int32
	Email         string
	FullName      string
	Nickname      sql.NullString
	ImageUrl      sql.NullString
	CommitteeID   sql.NullString
	CommitteeName sql.NullString
	DivisionID    sql.NullString
	DivisionName  sql.NullString
	PositionID    sql.NullString
	PositionName  sql.NullString
	HouseName     sql.NullString
	ContactNumber sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Interests     sql.NullString
	Discord       sql.NullString
	FbLink        sql.NullString
	Telegram      sql.NullString
}

func (q *Queries) GetMemberInfoById(ctx context.Context, id int32) (GetMemberInfoByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberInfoById, id)
	var i GetMemberInfoByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Nickname,
		&i.ImageUrl,
		&i.CommitteeID,
		&i.CommitteeName,
		&i.DivisionID,
		&i.DivisionName,
		&i.PositionID,
		&i.PositionName,
		&i.HouseName,
		&i.ContactNumber,
		&i.College,
		&i.Program,
		&i.Interests,
		&i.Discord,
		&i.FbLink,
		&i.Telegram,
	)
	return i, err
}

const getMemberRoles = `-- name: GetMemberRoles :many
SELECT r.id, r.name, r.description, mr.granted_by, mr.granted_at
FROM member_roles mr
JOIN roles r ON mr.role_id = r.id
WHERE mr.member_id = ?
`

type GetMemberRolesRow struct {
	ID          string
	Name        string
	Description sql.NullString
	GrantedBy   sql.NullInt32
	GrantedAt   sql.NullTime
}

func (q *Queries) GetMemberRoles(ctx context.Context, memberID int32) ([]GetMemberRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberRolesRow
	for rows.Next() {
		var i GetMemberRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersWithRole = `-- name: GetMembersWithRole :many
SELECT m.id, m.email, m.full_name, m.position_id, m.committee_id, mr.granted_at
FROM member_roles mr
JOIN members m ON mr.member_id = m.id
WHERE mr.role_id = ?
ORDER BY mr.granted_at DESC
`

type GetMembersWithRoleRow struct {
	ID          int32
	Email       string
	FullName    string
	PositionID  sql.NullString
	CommitteeID sql.NullString
	GrantedAt   sql.NullTime
}

func (q *Queries) GetMembersWithRole(ctx context.Context, roleID string) ([]GetMembersWithRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersWithRoleRow
	for rows.Next() {
		var i GetMembersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.PositionID,
			&i.CommitteeID,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleById = `-- name: GetRoleById :one
SELECT id, name, description FROM roles WHERE id = ?
`

func (q *Queries) GetRoleById(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleById, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, member_id, created_at, expires_at, last_activity, user_agent, ip_address
FROM sessions WHERE id = ? AND expires_at > NOW()
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getSessionWithMember = `-- name: GetSessionWithMember :one
SELECT 
    s.id, s.member_id, s.created_at, s.expires_at, s.last_activity, s.user_agent, s.ip_address,
    m.email, m.full_name
FROM sessions s
JOIN members m ON s.member_id = m.id
WHERE s.id = ? AND s.expires_at > NOW()
`

type GetSessionWithMemberRow struct {
	ID           string
	MemberID     int32
	CreatedAt    sql.NullTime
	ExpiresAt    time.Time
	LastActivity sql.NullTime
	UserAgent    sql.NullString
	IpAddress    sql.NullString
	Email        string
	FullName     string
}

func (q *Queries) GetSessionWithMember(ctx context.Context, id string) (GetSessionWithMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithMember, id)
	var i GetSessionWithMemberRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.UserAgent,
		&i.IpAddress,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO member_roles (member_id, role_id, granted_by) VALUES (?, ?, ?)
`

type GrantRoleParams struct {
	MemberID  int32
	RoleID    string
	GrantedBy sql.NullInt32
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.ExecContext(ctx, grantRole, arg.MemberID, arg.RoleID, arg.GrantedBy)
	return err
}

const hasRole = `-- name: HasRole :one
SELECT EXISTS(SELECT 1 FROM member_roles WHERE member_id = ? AND role_id = ?)
`

type HasRoleParams struct {
	MemberID int32
	RoleID   string
}

func (q *Queries) HasRole(ctx context.Context, arg HasRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasRole, arg.MemberID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS(SELECT 1 FROM member_roles WHERE member_id = ? AND role_id = 'ADMIN')
`

func (q *Queries) IsAdmin(ctx context.Context, memberID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAdmin, memberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAPIKeysByEmail = `-- name: ListAPIKeysByEmail :many
SELECT api_key_id, member_email, project, allowed_origin, is_dev, is_admin, created_at, expires_at FROM api_keys WHERE member_email = ? ORDER BY created_at DESC
`

type ListAPIKeysByEmailRow struct {
	ApiKeyID      int32
	MemberEmail   string
	Project       sql.NullString
	AllowedOrigin sql.NullString
	IsDev         bool
	IsAdmin       bool
	CreatedAt     sql.NullTime
	ExpiresAt     sql.NullTime
}

func (q *Queries) ListAPIKeysByEmail(ctx context.Context, memberEmail string) ([]ListAPIKeysByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByEmail, memberEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByEmailRow
	for rows.Next() {
		var i ListAPIKeysByEmailRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.MemberEmail,
			&i.Project,
			&i.AllowedOrigin,
			&i.IsDev,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT
    m.id,
    m.full_name,
    m.nickname,
    m.email,
    m.telegram,
    m.position_id,
    m.committee_id,
    m.college,
    m.program,
    m.discord,
    m.interests,
    m.contact_number,
    m.fb_link,
    m.image_url,
    h.name as house_name
FROM members m
LEFT JOIN houses h ON m.house_id = h.id
WHERE (? = '' OR FIND_IN_SET(m.position_id, ?))
  AND (? = '' OR FIND_IN_SET(m.committee_id, ?))
ORDER BY m.email
`

type ListMembersParams struct {
	PositionIds  string
	CommitteeIds string
}

type ListMembersRow struct {
	ID            int32
	FullName      string
	Nickname      sql.NullString
	Email         string
	Telegram      sql.NullString
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	HouseName     sql.NullString
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers,
		arg.PositionIds,
		arg.PositionIds,
		arg.CommitteeIds,
		arg.CommitteeIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Nickname,
			&i.Email,
			&i.Telegram,
			&i.PositionID,
			&i.CommitteeID,
			&i.College,
			&i.Program,
			&i.Discord,
			&i.Interests,
			&i.ContactNumber,
			&i.FbLink,
			&i.ImageUrl,
			&i.HouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM member_roles WHERE member_id = ? AND role_id = ?
`

type RevokeRoleParams struct {
	MemberID int32
	RoleID   string
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokeRole, arg.MemberID, arg.RoleID)
	return err
}

const storeAPIKey = `-- name: StoreAPIKey :exec
INSERT INTO api_keys (
    member_email,
    api_key_hash,
    project,
    allowed_origin,
    is_dev,
    is_admin,
    expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type StoreAPIKeyParams struct {
	MemberEmail   string
	ApiKeyHash    string
	Project       sql.NullString
	AllowedOrigin sql.NullString
	IsDev         bool
	IsAdmin       bool
	ExpiresAt     sql.NullTime
}

func (q *Queries) StoreAPIKey(ctx context.Context, arg StoreAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, storeAPIKey,
		arg.MemberEmail,
		arg.ApiKeyHash,
		arg.Project,
		arg.AllowedOrigin,
		arg.IsDev,
		arg.IsAdmin,
		arg.ExpiresAt,
	)
	return err
}

const updateMemberById = `-- name: UpdateMemberById :exec
UPDATE members SET
    full_name = ?,
    nickname = ?,
    email = ?,
    position_id = ?,
    committee_id = ?,
    college = ?,
    program = ?,
    house_id = ?,
    telegram = ?,
    discord = ?,
    interests = ?,
    contact_number = ?,
    fb_link = ?,
    image_url = ?
WHERE id = ?
`

type UpdateMemberByIdParams struct {
	FullName      string
	Nickname      sql.NullString
	Email         string
	PositionID    sql.NullString
	CommitteeID   sql.NullString
	College       sql.NullString
	Program       sql.NullString
	HouseID       sql.NullInt32
	Telegram      sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	ID            int32
}

func (q *Queries) UpdateMemberById(ctx context.Context, arg UpdateMemberByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberById,
		arg.FullName,
		arg.Nickname,
		arg.Email,
		arg.PositionID,
		arg.CommitteeID,
		arg.College,
		arg.Program,
		arg.HouseID,
		arg.Telegram,
		arg.Discord,
		arg.Interests,
		arg.ContactNumber,
		arg.FbLink,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}

const updateMemberSelf = `-- name: UpdateMemberSelf :exec

UPDATE members SET
    nickname = ?,
    telegram = ?,
    discord = ?,
    interests = ?,
    contact_number = ?,
    fb_link = ?,
    image_url = ?
WHERE id = ?
`

type UpdateMemberSelfParams struct {
	Nickname      sql.NullString
	Telegram      sql.NullString
	Discord       sql.NullString
	Interests     sql.NullString
	ContactNumber sql.NullString
	FbLink        sql.NullString
	ImageUrl      sql.NullString
	ID            int32
}

// Member profile update queries
func (q *Queries) UpdateMemberSelf(ctx context.Context, arg UpdateMemberSelfParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberSelf,
		arg.Nickname,
		arg.Telegram,
		arg.Discord,
		arg.Interests,
		arg.ContactNumber,
		arg.FbLink,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity = NOW() WHERE id = ?
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, id)
	return err
}
