// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package repository

import (
	"context"
	"database/sql"
)

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, description FROM roles ORDER BY id
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberAuthInfo = `-- name: GetMemberAuthInfo :one
SELECT id, position_id, committee_id FROM members WHERE email = ?
`

type GetMemberAuthInfoRow struct {
	ID          int32
	PositionID  sql.NullString
	CommitteeID sql.NullString
}

// lightweight query for authorization checks (no image_url dependency)
func (q *Queries) GetMemberAuthInfo(ctx context.Context, email string) (GetMemberAuthInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberAuthInfo, email)
	var i GetMemberAuthInfoRow
	err := row.Scan(&i.ID, &i.PositionID, &i.CommitteeID)
	return i, err
}

const getMemberRoles = `-- name: GetMemberRoles :many
SELECT r.id, r.name, r.description, mr.granted_by, mr.granted_at
FROM member_roles mr
JOIN roles r ON mr.role_id = r.id
WHERE mr.member_id = ?
`

type GetMemberRolesRow struct {
	ID          string
	Name        string
	Description sql.NullString
	GrantedBy   sql.NullInt32
	GrantedAt   sql.NullTime
}

func (q *Queries) GetMemberRoles(ctx context.Context, memberID int32) ([]GetMemberRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberRolesRow
	for rows.Next() {
		var i GetMemberRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersWithRole = `-- name: GetMembersWithRole :many
SELECT m.id, m.email, m.full_name, m.position_id, m.committee_id, mr.granted_at
FROM member_roles mr
JOIN members m ON mr.member_id = m.id
WHERE mr.role_id = ?
ORDER BY mr.granted_at DESC
`

type GetMembersWithRoleRow struct {
	ID          int32
	Email       string
	FullName    string
	PositionID  sql.NullString
	CommitteeID sql.NullString
	GrantedAt   sql.NullTime
}

func (q *Queries) GetMembersWithRole(ctx context.Context, roleID string) ([]GetMembersWithRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, getMembersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersWithRoleRow
	for rows.Next() {
		var i GetMembersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.PositionID,
			&i.CommitteeID,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleById = `-- name: GetRoleById :one
SELECT id, name, description FROM roles WHERE id = ?
`

func (q *Queries) GetRoleById(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleById, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO member_roles (member_id, role_id, granted_by) VALUES (?, ?, ?)
`

type GrantRoleParams struct {
	MemberID  int32
	RoleID    string
	GrantedBy sql.NullInt32
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.ExecContext(ctx, grantRole, arg.MemberID, arg.RoleID, arg.GrantedBy)
	return err
}

const hasRole = `-- name: HasRole :one
SELECT EXISTS(SELECT 1 FROM member_roles WHERE member_id = ? AND role_id = ?)
`

type HasRoleParams struct {
	MemberID int32
	RoleID   string
}

func (q *Queries) HasRole(ctx context.Context, arg HasRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasRole, arg.MemberID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS(SELECT 1 FROM member_roles WHERE member_id = ? AND role_id = 'ADMIN')
`

func (q *Queries) IsAdmin(ctx context.Context, memberID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAdmin, memberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM member_roles WHERE member_id = ? AND role_id = ?
`

type RevokeRoleParams struct {
	MemberID int32
	RoleID   string
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokeRole, arg.MemberID, arg.RoleID)
	return err
}
