// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, member_id, expires_at, user_agent, ip_address)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	MemberID  int32
	ExpiresAt time.Time
	UserAgent sql.NullString
	IpAddress sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.MemberID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const deleteAllSessionsForMember = `-- name: DeleteAllSessionsForMember :exec
DELETE FROM sessions WHERE member_id = ?
`

func (q *Queries) DeleteAllSessionsForMember(ctx context.Context, memberID int32) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsForMember, memberID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = ?, last_activity = NOW() WHERE id = ?
`

type ExtendSessionParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, member_id, created_at, expires_at, last_activity, user_agent, ip_address
FROM sessions WHERE id = ? AND expires_at > NOW()
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getSessionWithMember = `-- name: GetSessionWithMember :one
SELECT 
    s.id, s.member_id, s.created_at, s.expires_at, s.last_activity, s.user_agent, s.ip_address,
    m.email, m.full_name
FROM sessions s
JOIN members m ON s.member_id = m.id
WHERE s.id = ? AND s.expires_at > NOW()
`

type GetSessionWithMemberRow struct {
	ID           string
	MemberID     int32
	CreatedAt    sql.NullTime
	ExpiresAt    time.Time
	LastActivity sql.NullTime
	UserAgent    sql.NullString
	IpAddress    sql.NullString
	Email        string
	FullName     string
}

func (q *Queries) GetSessionWithMember(ctx context.Context, id string) (GetSessionWithMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithMember, id)
	var i GetSessionWithMemberRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.UserAgent,
		&i.IpAddress,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity = NOW() WHERE id = ?
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, id)
	return err
}
