---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Build
        run: make build
        # run: go build -v ./...

    # - name: Test with the Go CLI
    #   run: make test
    #   run: go test ./...

